import sys
from pathlib import Path

GLOBAL_DIR = Path(__file__).parent / ".."
sys.path.append(str(GLOBAL_DIR))


GENERATED_PATH = str(GLOBAL_DIR / "generated")
DATA_PATH = str(GLOBAL_DIR / "data")
EYE_TRACKING_PATH = f"{DATA_PATH}/eye_tracking"
SETS_PATH = f"{DATA_PATH}/sets"
DEPTH_PATH = f"{DATA_PATH}/depth"
SALIENCY_PATH = f"{DATA_PATH}/saliency"
IMAGES_PATH = f"{DATA_PATH}/images"

EYE_TRACKING_RAW_PATH = f"{EYE_TRACKING_PATH}/raw"
EYE_TRACKING_PROCESSED_PATH = f"{EYE_TRACKING_PATH}/processed"
DEPTH_MAP_IMG_PATH = f"{DEPTH_PATH}/map_images"
DEPTH_MAP_PFM_PATH = f"{DEPTH_PATH}/map_pfm"
DEPTH_SEG_IMG_PATH = f"{DEPTH_PATH}/segmented_images"
DEPTH_SEG_PFM_PATH = f"{DEPTH_PATH}/segmented_pfm"
SALIENCY_MAP_IMG_PATH = f"{SALIENCY_PATH}/map_images"
SALIENCY_MAP_PFM_PATH = f"{SALIENCY_PATH}/map_pfm"

PROCESSED_EYE_TRACKING_FILE_NAME = "data.csv"


RAW_EYE_TRACKING_FRAME_WIDTH = 6144
RAW_EYE_TRACKING_FRAME_HEIGHT = 3072
